Productserver
aguazul-marco/pivot pull request #1
Opened 2022-11-01 23:56 UTC by aguazul-marco

Homework assignment

2022-11-02 02:53 UTC, jboursiquot requested changes

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +				log.Fatal(err)
Don't use `Fatal` here. It'll crash your application if an encoding error were to occur. Handle the error (perhaps log it or return a 500 status code) but do not crash your own server.

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +		} else {
No need for the `else`. Use the response writing to send back the `http.StatusNoFound`.

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +		log.Fatal(err)
Do not crash your own server on an encoding error.

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +				log.Fatal(err)
Do not crash your own server.

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +				log.Fatal(err)
Do not crash your own server.

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +			_ = json.NewDecoder(r.Body).Decode(&product)
Handle your errors.

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +	_ = json.NewDecoder(r.Body).Decode(&product)
Handle your errors.

2022-11-02 02:53 UTC, jboursiquot commented on productserver/main.go
> +		log.Fatal(err)
Do not crash your own server.

2022-11-03 22:58 UTC, jboursiquot requested changes
Respond to the client with the appropriate HTTP status codes.

2022-11-03 22:58 UTC, jboursiquot commented on productserver/main.go
> +				log.Println(http.StatusInternalServerError)
You need to respond back to the client with these status codes, not just log them.

2022-11-04 22:09 UTC, aguazul-marco commented
I've updated the my error responses

2022-11-05 00:12 UTC, jboursiquot requested changes

2022-11-05 00:12 UTC, jboursiquot commented on productserver/main.go
> +	r.HandleFunc("/products", GetProducts).Methods("GET")
Test your server to ensure you're able to reach all the routes as intended. Order of the routes matters.

2022-11-05 00:12 UTC, jboursiquot commented on productserver/main.go
> +		fmt.Println("error occured while encoding")
Use the `log` package instead of `fmt` and include the `err` in your output to make it more useful.

2022-11-05 00:12 UTC, jboursiquot commented on productserver/main.go
> +		w.WriteHeader(http.StatusNotFound)
Shouldn't this be outside of your loop? You only know the product by the given ID was not found once you've gone through all of the products in the list, right?

2022-11-05 00:12 UTC, jboursiquot commented on productserver/main.go
> +			ID, err := strconv.Atoi(id)
Get in the habit of using lowercased variable names or mixedCase names. Remember, capitalization matters in Go.

2022-11-07 14:50 UTC, jboursiquot approved these changes

2022-11-07 21:31 UTC, merged