Marvel Client API assignment
aguazul-marco/pivot pull request #3
Opened 2022-11-10 01:50 UTC by aguazul-marco

2022-11-10 02:30 UTC, jboursiquot requested changes
You've submitted a duplicate of the example I did in class.
Read the assignment again: https://fifth-bottom-224.notion.site/Build-a-Marvel-Client-669c3b397f844a96a6e6d4659ca20cb3

And try to work through the solution from scratch, only using my example as a reference so that it does not look like you simply copied my code.

Let me know if you need some one-on-one assistance.

2022-11-10 23:01 UTC, aguazul-marco commented
Code Output:
```
([]marvel.Character) (len=5 cap=6) {
 (marvel.Character) {
  ID: (int) 1011334,
  Name: (string) (len=7) "3-D Man",
  Description: (string) ""
 },
 (marvel.Character) {
  ID: (int) 1017100,
  Name: (string) (len=12) "A-Bomb (HAS)",
  Description: (string) (len=302) "Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! "
 },
 (marvel.Character) {
  ID: (int) 1009144,
  Name: (string) (len=6) "A.I.M.",
  Description: (string) (len=61) "AIM is a terrorist organization bent on destroying the world."
 },
 (marvel.Character) {
  ID: (int) 1010699,
  Name: (string) (len=11) "Aaron Stack",
  Description: (string) ""
 },
 (marvel.Character) {
  ID: (int) 1009146,
  Name: (string) (len=26) "Abomination (Emil Blonsky)",
  Description: (string) (len=236) "Formerly known as Emil Blonsky, a spy of Soviet Yugoslavian origin working for the KGB, the Abomination gained his powers after receiving a dose of gamma radiation similar to that which transformed Bruce Banner into the incredible Hulk."
 }
}
```

2022-11-12 03:29 UTC, jboursiquot requested changes

2022-11-12 03:29 UTC, jboursiquot commented on cmd/marvel-client/types.go
> +package main
This should be part of package `marvel`, not `main`.

2022-11-12 03:29 UTC, jboursiquot commented on cmd/marvel-client/main.go
> +	spew.Dump(character)
The assignment calls for listing out the name and description of the characters, not a dump.

2022-11-12 03:29 UTC, jboursiquot commented on marvel/marvel.go
> +func (c *Client) GetCharacter(limit int) ([]Character, error) {
You're retrieving a list of characters -- plural. This method name could use a tweak, don't you agree?

2022-11-12 12:56 UTC, aguazul-marco commented
Output:
```
Character: 3-D Man
Description: 

Character: A-Bomb (HAS)
Description: Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! 

Character: A.I.M.
Description: AIM is a terrorist organization bent on destroying the world.

Character: Aaron Stack
Description: 

Character: Abomination (Emil Blonsky)
Description: Formerly known as Emil Blonsky, a spy of Soviet Yugoslavian origin working for the KGB, the Abomination gained his powers after receiving a dose of gamma radiation similar to that which transformed Bruce Banner into the incredible Hulk.
```

2022-11-12 16:09 UTC, jboursiquot approved these changes
Well done.

2022-11-15 00:09 UTC, merged