Part 1 of Database-Driven Product Server assignment.
aguazul-marco/pivot pull request #4
Opened 2022-11-29 01:56 UTC by aguazul-marco

Evening Johnny! I figured i'd get some feedback on part 1 of the assignment while I continue to work on part 2. Thank you.

2022-11-29 01:56 UTC, aguazul-marco commented
Copy of the output
`ID: 1
Name: Water - San Pellegrino
Price: 80
ID: 2
Name: Cape Capensis - Fillet
Price: 53
ID: 3
Name: Bread - Bistro Sour
Price: 22
ID: 4
Name: Lamb - Shoulder
Price: 16
ID: 5
Name: Lettuce - Arugula
Price: 11`

2022-11-29 23:02 UTC, jboursiquot requested changes
You have things in here that do not belong to this assignment. Clean up and resubmit.

2022-11-29 23:02 UTC, jboursiquot commented on cmd/seeder/main.go
> +func seed(db *sql.DB) error {
It would have been better to pass in the list of products as an argument rather than use a global.

2022-12-02 02:51 UTC, aguazul-marco commented
I removed the directories that didn't belong to the assignment and made the updates requested.

2022-12-03 18:16 UTC, jboursiquot requested changes

2022-12-03 18:16 UTC, jboursiquot commented on cmd/seeder/main.go
> +func initProduct() {
`initProducts` is better name

2022-12-03 18:16 UTC, jboursiquot commented on cmd/seeder/main.go
> +func initProduct() {
Return the `[]Product` here.
Better yet `func initProducts(path string)([]Product, error)`

2022-12-03 18:16 UTC, jboursiquot commented on cmd/seeder/main.go
> +	initProduct()
Capture the list of products and do something about the possible error returned.

2022-12-03 18:16 UTC, jboursiquot commented on cmd/seeder/main.go
> +	for _, product := range Products {
Use lowercase `products`

2022-12-03 18:16 UTC, jboursiquot commented on cmd/seeder/main.go
> +	Products = products
You don't need this

2022-12-04 00:58 UTC, aguazul-marco commented
I updated the initProducts func as well as the variable names we discussed

2022-12-04 01:11 UTC, jboursiquot requested changes

2022-12-04 01:11 UTC, jboursiquot commented on cmd/seeder/main.go
> +var Products []Product
You don't need this global.

2022-12-04 01:11 UTC, jboursiquot commented on cmd/seeder/main.go
> +	var newProducts []Product
No need to for this. Just print out each product you read from the DB during the for loop over `rows`.

2022-12-04 01:11 UTC, jboursiquot commented on cmd/seeder/main.go
> +	}
No need for this again. You're already looping over the rows. Output during that loop.

2022-12-04 01:29 UTC, aguazul-marco commented
Removed the global []products and for loop at the end.

2022-12-04 01:43 UTC, jboursiquot requested changes

2022-12-08 00:03 UTC, jboursiquot requested changes
Minor change. Nice work.

2022-12-08 02:45 UTC, jboursiquot approved these changes

2022-12-08 20:59 UTC, merged