Add CI
aguazul-marco/pivot pull request #7
Opened 2022-12-03 01:24 UTC by aguazul-marco

Acceptance Criteria - Part 1

2022-12-03 01:31 UTC, aguazul-marco commented
Evening Johnny. I'm not sure why my prior commits are listed on this branch as well.

2022-12-03 20:50 UTC, jboursiquot requested changes
You've got non-CI work in here. Remove.

2022-12-04 04:25 UTC, aguazul-marco commented
Removed non-CI work.

2022-12-06 04:23 UTC, jboursiquot approved these changes

2022-12-08 21:00 UTC, merged