Add pow
aguazul-marco/pivot pull request #8
Opened 2022-12-03 06:58 UTC by aguazul-marco

Acceptance Criteria - Part 2

2022-12-03 20:50 UTC, jboursiquot requested changes
You've got non-related work in here. Remove.

2022-12-04 04:29 UTC, aguazul-marco commented
Removed non-related work.

2022-12-06 04:24 UTC, jboursiquot approved these changes

2022-12-08 21:22 UTC, aguazul-marco commented
Hey Johnny! Sorry to bug you but I wanted to see if you could assist me. I'm unable to merge this branch to the main due to a conflicting file `cmd/seeder/main.go`. I removed the file already but it still won't let me merge. Any input would be greatly appreciated. Thank you

2022-12-12 17:22 UTC, jboursiquot approved these changes

2022-12-17 20:52 UTC, closed without merging